<?php
/**
 * Defines a new permission.
 *
 * Implements hook_permission().
 */
function hide_sticky_promote_permission() {
  return array(
    'sticky and promote' => array(
      'title' => t('Use sticky and promoted options'),
      'description' => t("Allows use of the 'Sticky at top of lists' and 'Promoted to front page' options"),
      'restrict access' => TRUE,
    ),
  );
}

/**
 * Remove sticky/promote entirely from add and edit content type forms.
 *
 * Implements hook_form_FORM_ID_alter().
 */
function hide_sticky_promote_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  // Remove sticky/promote entirely from add and edit content type forms.
  // check permissions first 
  if (!user_access('sticky and promote')) {
    $options = array('promote', 'sticky');
    foreach ($options as $key) {
      unset($form['workflow']['node_options']['#options'][$key]);    
    }
  }
}

/**
 * Remove sticky/promote entirely from node/X/edit & node/X/add forms.
 * 
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function hide_sticky_promote_form_node_form_alter(&$form, &$form_state, $form_id) {
  // check permissions first 
  if (!user_access('sticky and promote')) {
    $options = array('promote', 'sticky');
    foreach ($options as $key) {
      $form['options'][$key]['#access'] = FALSE;
    }
  }
}

/**
 * Remove some sticky/promote update options on admin/content.
 *
 * Implements hook_form_FORM_ID_alter().
 */
function hide_sticky_promote_form_node_admin_content_alter(&$form, &$form_state, $form_id) {
  // check permissions first 
  if (!user_access('sticky and promote')) {
    $options = array('demote', 'promote', 'sticky', 'unsticky', );
    foreach ($options as $key) {
      unset($form['admin']['options']['operation']['#options'][$key]);
    }
  }
}

/**
 * Some help for users.
 *
 * Implements hook_help().
 */
function hide_sticky_promote_help($path, $arg) {
  switch ($path) {
    case 'admin/setting/hide_sticky_promote':
      return t("Once enabled this module removes the 'sticky' and 'promote to front page' options from content creation/editing sections. Under Permissions you can allow user roles to override the default and use the 'sticky' and 'promote to front page' options /admin/people/permissions");
      break;
      
    case 'admin/help#hide_sticky_promote': 
      $helpTxt = t("Once enabled this module removes the 'sticky' and 'promote to front page' options from content creation/editing sections. Under Permissions you can allow user roles to override the default and use the 'sticky' and 'promote to front page' options /admin/people/permissions");
      return $helpTxt;    
    break;
  }
}
