<?php

/**
 * Defines a new permission
 *
 * Implements hook_permission().
 */
function hide_sticky_promote_permission() {
  return array(
    'sticky and promote' => array(
      'title' => t('Usage of sticky and promoted options'),
      'description' => t('Usage of "Sticky at top of lists" and "Promoted to front page" options'),
      'restrict access' => TRUE
    ),
  );
}

/**
 * Remove sticky/promote entirely from add and edit content type forms.
 *
 * Implements hook_form_FORM_ID_alter().
 */
function hide_sticky_promote_form_node_type_form_alter(&$form, &$form_state, $form_id) {
  // Remove sticky/promote entirely from add and edit content type forms.
  // check permissions first 
  global $user;
  if (!user_access('sticky and promote')) {
    $options = array('promote', 'sticky');
    foreach ($options as $key) {
      unset($form['workflow']['node_options']['#options'][$key]);    
    }
  }
}

/**
 * Remove sticky/promote entirely from node/X/edit & node/X/add forms.
 * 
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function hide_sticky_promote_form_node_form_alter(&$form, &$form_state, $form_id) {
  // check permissions first 
  global $user;
  if (!user_access('sticky and promote')) {
    $options = array('promote', 'sticky');
    foreach ($options as $key) {
      $form['options'][$key]['#access'] = FALSE;
    }
  }
}

/**
 * Remove some sticky/promote update options on admin/content.
 *
 * Implements hook_form_FORM_ID_alter().
 */
function hide_sticky_promote_form_node_admin_content_alter(&$form, &$form_state, $form_id) {
  // check permissions first 
  global $user;
  if (!user_access('sticky and promote')) {
    $options = array('demote', 'promote', 'sticky', 'unsticky', );
    foreach ($options as $key) {
      unset($form['admin']['options']['operation']['#options'][$key]);
    }
  }
}

/**
 * Some help for users
 *
 * Implements hook_help().
 */
function hide_sticky_promote_help($path, $arg) {
  switch($path){
    case 'admin/setting/hide_sticky_promote':
      return 'To setup this module just go to Permision page (admin/people/permissions) and assign permission "Usage of sticky and promoted options" to roles which can use these options';
      break;
    case 'admin/help#hide_sticky_promote'; 
      $helpTxt='<p>To setup this module just go to Permision page (admin/people/permissions) and assign permission "Usage of sticky and promoted options" to roles which can use these options</p>';
      return $helpTxt;    
    break;
  }
}
